name: Gate-level Preconfigured Simulation

on:
# No need to enable this for each PR. Typically, if RTL passed, gate-level should pass as well
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

# Environment variables
env:
  # The HDL simulator to be used
  SIM: vcs
  # NUmber of simulation jobs in parallel
  NUM_JOBS: 4

jobs:
  preconfig_simulation_dp:
    name: Simulation
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        fabric_name: ["ultimate"]
        benchmark_suite_name: ["checkin", "ff", "dsp", "bram", "qor"]
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Checkout submodule
        run: |
          make checkout_dv

      - name: Create benchmark links
        shell: bash
        run: |
          cd benchmarks
          make all

      - name: Uncompress bitstream
        shell: bash
        run: |
          make uncompress_bitstream FABRIC_NAME=${{ matrix.fabric_name }} BENCHMARK_SUITE_NAME=${{ matrix.benchmark_suite_name }}

      - name: Link PDK
        shell: bash
        run: |
          cd pdk
          make link

      - name: Run simulation
        shell: bash
        run: |
          cd dv
          make run_preconfig_cocotb FABRIC_NAME=${{ matrix.fabric_name }} BENCHMARK_SUITE_NAME=${{ matrix.benchmark_suite_name }} NETLIST_TYPE=gl SIM=$SIM NUM_JOBS=$NUM_JOBS
