name: RTL Preconfigured Simulation

# Only run for pull requests as we care contribution to the master
# - There are changes in RTL files
on:
  pull_request:
    path:
      - ".github/**"
      - "arch/**"
      - "benchmarks/**"
      - "rtl/**"
      - "dv/**"
      - "openfpga_tasks/**"
      - "Makefile"
      - "utils/**"
  push:
    branches:
      - 'main'

# Environment variables
env:
  # The HDL simulator to be used
  SIM: vcs
  # NUmber of simulation jobs in parallel
  NUM_JOBS: 4

jobs:
  detect_arch_changes:
    runs-on: ubuntu-latest
    outputs:
      source_modified: ${{ steps.git-diff-arch.outputs.source_modified }}
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout code
        uses: actions/checkout@v2.1.0

      - name: Detect architecture/script changes
        id: git-diff-arch
        run: |
          git fetch
          git diff origin/main HEAD --name-status -- ':.github/**' ':arch/**' ':benchmarks/**' ':openfpga_tasks/**' 'Makefile' 'utils/**' ':rtl/**' 'dv/**'
          if git diff origin/main HEAD --name-status --exit-code -- ':.github/**' ':arch/**' ':benchmarks/**' ':openfpga_tasks/**' 'Makefile' 'utils/**' ':rtl/**' 'dv/**'; then
            echo "::set-output name=source_modified::false"
          else
            echo "Detect changes in RTL and bitstreams. Require verification"
            echo "::set-output name=source_modified::true"
          fi

  preconfig_simulation:
    name: Preconfigured testbench simulation
    needs: detect_arch_changes
    runs-on: [self-hosted, Linux, X64]
    # Triggered when a pull request is a label of 'force_rtl_preconfig_simulation' or on main branch
    if: needs.detect_arch_changes.outputs.source_modified == 'true' || contains(github.event.pull_request.labels.*.name, 'force_rtl_preconfig_simulation') || github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        fabric_name: ["ultimate"]
        benchmark_suite_name: ["checkin", "ff", "dsp", "bram", "qor"]
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Checkout submodule
        run: |
          make checkout_dv

      - name: Create benchmark links
        shell: bash
        run: |
          cd benchmarks
          make all

      - name: Uncompress bitstream
        shell: bash
        run: |
          make uncompress_bitstream FABRIC_NAME=${{ matrix.fabric_name }} BENCHMARK_SUITE_NAME=${{ matrix.benchmark_suite_name }}

      - name: Link PDK
        shell: bash
        run: |
          cd pdk
          make link

      - name: Run simulation
        shell: bash
        run: |
          cd dv
          make run_preconfig_cocotb FABRIC_NAME=${{ matrix.fabric_name }} BENCHMARK_SUITE_NAME=${{ matrix.benchmark_suite_name }} NETLIST_TYPE=rtl SIM=$SIM NUM_JOBS=$NUM_JOBS
