name: Fabric Generation

# Only run for pull requests as we care contribution to the master
# - There are changes in RTL files
on:
  pull_request:
    path:
      - ".github/**"
      - "arch/**"
      - "benchmarks/**"
      - "openfpga_tasks/**"
      - "Makefile"
      - "utils/**"
  push:
    branches:
      - 'main'

jobs:
  detect_arch_changes:
    runs-on: ubuntu-latest
    outputs:
      source_modified: ${{ steps.git-diff-arch.outputs.source_modified }}
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout code
        uses: actions/checkout@v2.1.0

      - name: Detect architecture/script changes
        id: git-diff-arch
        run: |
          git fetch
          git diff origin/main HEAD --name-status -- ':.github/**' ':arch/**' ':benchmarks/**' ':openfpga_tasks/**' 'Makefile' 'utils/**'
          if git diff origin/main HEAD --name-status --exit-code -- ':.github/**' ':arch/**' ':benchmarks/**' ':openfpga_tasks/**' 'Makefile' 'utils/**'; then
            echo "::set-output name=source_modified::false"
          else
            echo "Detect changes in architecture and related scripts. Require netlist generation"
            echo "::set-output name=source_modified::true"
          fi

  generate_netlist:
    name: Netlist generation
    needs: detect_arch_changes
    # Triggered when a pull request is a label of 'force_netlist_generation' or on main branch
    if: needs.detect_arch_changes.outputs.source_modified == 'true' || contains(github.event.pull_request.labels.*.name, 'force_netlist_generation') || github.ref == 'refs/heads/main'
    runs-on: [self-hosted, Linux, X64]
    outputs:
      # this is output as string, see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idoutputs
      golden_modified: ${{ steps.changes.outputs.status_code == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        fabric_name: ["dp", "ultimate"]
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
          mkdir -p "${{ github.workspace }}"

      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Checkout submodule
        run: |
          make checkout_benchmarks

      - name: Create benchmark links
        shell: bash
        run: |
          cd benchmarks
          make all

      - name: Running fabric generation
        shell: bash
        run: |
          make fabric FABRIC_NAME=${{ matrix.fabric_name }}

      - name: Detect changes on golden
        id: git-diff-golden
        run: |
          git diff --name-status -- ':rtl/${{ matrix.fabric_name }}/**'
          if git diff --name-status --exit-code -- ':rtl/${{ matrix.fabric_name }}/**'; then
            echo "::set-output name=golden_changes::false"
          else
            echo "Detect changes in output netlists. Require netlist verification"
            echo "::set-output name=golden_changes::true"
          fi

      - name: Show flag on golden changes
        run: |
          echo "git-diff output: ${{steps.git-diff-golden.outputs.golden_changes}}"

      - name: Check consistency with golden
        if: steps.git-diff-golden.outputs.golden_changes == 'true'
        run: |
          echo "Golden results are changed. Request further review!"
          echo "Detailed changes are shown below:"
          git diff -- ':rtl/${{ matrix.fabric_name }}/**'
          exit 1
